# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca65d34106cb16e063f2debb1d52a58d84b00f0c46ad54c27f3c72a461c8f4d3b56e8cb94a3928734f69f48991f4d9bf16d9910d52f5b91f59c4950a20a5a2d

test:
  secret_key_base: e890ea8b62f7d55c5fa341bf9309c2e38d81f61d782cc95d13c5140f5b1f837679ce2edfba1fe23ce7deb5c45591f7b27318e97ee394ff098e48ab2a280d6005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
